openbuildxyz/Web3-Frontend-Bootcamp

members/zzworker/readme.md
=> zzworker readme

members/bcyangxu/readme.md
=> sign up for bcyangxu

members/Alexzhuangyao/readme.md
=> feat: sign in alexzhuangyao

members/carola-niu/readme.md
=> init: carola-niu

members/Raincal/readme.md
=> init: Raincal

members/huzhengen/readme.md
=> init: huzhengen

members/pol117/readme.md
=> feat: 注册报名

members/keyding/readme.md
=> Register and sign up

members/code342/readme.md
=> init: code342

members/humbornjo/readme.md
=> init: humbornjo

members/chefuny/readme.md
=> init: chefuny

members/limsenkeat/readme.md
Registered with personal info.
=> init: limsenkeat

members/WAIYIN-tech/readme.md
=> init: WAIYIN-tech

members/JeremyZ/readme.md
=> init: JeremyZ

members/STAJJJ/readme.md
=> init: STAJJJ

members/AhDEV-free/readme.md
=> init: AhDEV-free

members/TomatoDroid/readme.md
=> init: TomatoDroid

members/blackdogTT/readme.md
=> init: blackdogTT

members/jerikchan/readme.md
=> init: jerikchan

members/haobarry/readme.md
=> init: barry

members/Sifotd/readme.md
=> init: Sifotd

members/Yunfei1982/readme.md
=> init: Yunfei1982

members/Yaqioooong/readme.md
=> init Yaqioooong

members/LeonXDH/readme.md
=> init：LeonXDH

members/Wujerry/readme.md
=> init: Wujerry

members/zhengbangbo/readme.md
=> init: zhengbangbo

members/soldcoin/readme.md
=> Bootcamp registration

members/zhtkeepup/readme.md
=> add personal info

members/WangEn/readme.md
=> init: WangEn

members/zpjayyy/readme.md
=> init zpjayyy

members/hwwang2/readme.md
=> init: hwwang2

members/aiyoudiao/readme.md
=> init: aiyoudiao

members/Josh-hub01/readme.md
=> init: josh

members/Tsuizen/readme.md
=> init: Tsuizen

members/huangkuaikuai/readme.md
=> init: huangkuaikuai

members/yywhyting/readme.md
=> init:yywhyting

members/luyaoLee/readme.md
=> init: luyaoLee

members/bravehot/readme.md
=> init: bravehot

members/aliyan404/readme.md
=> init: aliyan404

members/bytesloop/readme.md
=> init: bytesloop

members/liulvcheng/readme.md
=> init: liulvcheng

members/nolank128/readme.md
=> init: Kason

members/hundren/readme.md
=> init: hundren

members/b-t-s-1/readme.md
=> init:b-t-s-1

members/hbrls/readme.md
=> init: hbrls

members/0xorz/readme.md
注册，原始pr为：https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/pull/214
=> init: 0xorz

members/DeJeune/readme.md
=> task1: DeJeune

members/kepplow/readme.md
=> init: DRose

members/0xorz/task1/.eslintrc.cjs, members/0xorz/task1/.gitignore, members/0xorz/task1/index.html, members/0xorz/task1/package-lock.json, members/0xorz/task1/package.json, members/0xorz/task1/src/AddToDo.jsx, members/0xorz/task1/src/App.jsx, members/0xorz/task1/src/Header.jsx, members/0xorz/task1/src/ToDoItem.jsx, members/0xorz/task1/src/ToDoList.jsx, members/0xorz/task1/src/main.jsx, members/0xorz/task1/vite.config.js
=> task1: 0xorz

members/hbrls/readme.md
=> task1: hbrls

members/MercuryZy/readme.md
=> Init: MercuryZy

members/saltand/readme.md
=> init: saltand

members/azyliu/readme.md
=> init: yzayza

members/billyma128/README.md
=> init: billyma128

members/elliotxin/readme.md
=> init: elliotxin

members/Yolo-00/readme.md
=> init: Yolo-00

members/FrankChencc/readme.md
=> init: FrankChencc

members/memory713/readme.md
=> init: memory713

members/Debbl/readme.md
=> init: Debbl

members/YagamiNewLight/readme.md
=> init: YagamiNewLight

members/tiantianwork/readme.md
=> init: tiantianwork

members/Yolandatsai/readme.md
=> init: Yolandatsai

members/Pithos23/readme.md
=> init: Pithos23

members/Chen-Lun-Hao/readme.md
=> init: Chen-Lun-Hao

members/threshermagnus484159/readme.md
=> init：threshermagnus484159

members/liuzizi0505/readme.md
=> init: liuzizi0505

members/kakuro9/readme.md
=> init: kakuro9

members/shuhaoLIN/readme.md
=> init: linshuhao1017

members/flytam/task1/todo-list/.eslintrc.cjs, members/flytam/task1/todo-list/.gitignore, members/flytam/task1/todo-list/README.md, members/flytam/task1/todo-list/index.html, members/flytam/task1/todo-list/package-lock.json, members/flytam/task1/todo-list/package.json, members/flytam/task1/todo-list/src/AddToDo.tsx, members/flytam/task1/todo-list/src/App.tsx, members/flytam/task1/todo-list/src/Header.tsx, members/flytam/task1/todo-list/src/ToDoItem.tsx, members/flytam/task1/todo-list/src/ToDoList.tsx, members/flytam/task1/todo-list/src/main.tsx, members/flytam/task1/todo-list/src/types.ts, members/flytam/task1/todo-list/src/vite-env.d.ts, members/flytam/task1/todo-list/tsconfig.json, members/flytam/task1/todo-list/tsconfig.node.json, members/flytam/task1/todo-list/vite.config.ts
=> task1: flytam

members/luAmy/readme.md
=> init: luAmy

members/polariscx/readme.md
=> init: polariscx

members/linhaishe/readme.md
=> init: linhaishe

members/muuyao/readme.md
=> init: muuyao

members/Y2511525406/readme.md
=> init: Y2511525406

members/rzexin/readme.md
=> init: rzexin

members/1473303013/task1/todo-list/.eslintrc.cjs, members/1473303013/task1/todo-list/.gitignore, members/1473303013/task1/todo-list/README.md, members/1473303013/task1/todo-list/index.html, members/1473303013/task1/todo-list/package-lock.json, members/1473303013/task1/todo-list/package.json, members/1473303013/task1/todo-list/src/AddToDo.tsx, members/1473303013/task1/todo-list/src/App.tsx, members/1473303013/task1/todo-list/src/Header.tsx, members/1473303013/task1/todo-list/src/ToDoItem.tsx, members/1473303013/task1/todo-list/src/ToDoList.tsx, members/1473303013/task1/todo-list/src/main.tsx, members/1473303013/task1/todo-list/src/types.ts, members/1473303013/task1/todo-list/src/vite-env.d.ts, members/1473303013/task1/todo-list/tsconfig.json, members/1473303013/task1/todo-list/tsconfig.node.json, members/1473303013/task1/todo-list/vite.config.ts
=> task1: 1473303013

members/jamie-ji/readme.md
=> Init: jamie-ji

members/chanhohn/readme.md, members/hedgehog/readme.md
* GitHub ID: hedgehog
* OpenBuild Username: hedgehog
* ERC20 钱包地址: 0x742F1AD3b2C139926Ad5D789fDbf6C4ae2d99EA9
前端小白，web3小白
=> init:chanhohn

members/Draculabo/readme.md
=> init: Draculabo

members/604137978/task1/todo-list/.eslintrc.cjs, members/604137978/task1/todo-list/.gitignore, members/604137978/task1/todo-list/README.md, members/604137978/task1/todo-list/index.html, members/604137978/task1/todo-list/package-lock.json, members/604137978/task1/todo-list/package.json, members/604137978/task1/todo-list/src/AddToDo.tsx, members/604137978/task1/todo-list/src/App.tsx, members/604137978/task1/todo-list/src/Header.tsx, members/604137978/task1/todo-list/src/ToDoItem.tsx, members/604137978/task1/todo-list/src/ToDoList.tsx, members/604137978/task1/todo-list/src/main.tsx, members/604137978/task1/todo-list/src/types.ts, members/604137978/task1/todo-list/src/vite-env.d.ts, members/604137978/task1/todo-list/tsconfig.json, members/604137978/task1/todo-list/tsconfig.node.json, members/604137978/task1/todo-list/vite.config.ts
=> task1: 604137978

members/leon-kay/readme.md
=> init:leon-kay

members/0xhutou/readme.md
=> init: 0xhutou

members/fyh2001/readme.md
=> init: fyh2001

members/AlexL0ng/readme.md
=> init: AlexL0ng

members/ymjrcc/readme.md
=> init: ymjrcc

members/qq1456680570/README.md
=> init: qq1456680570

members/coconal/readme.md
=> init: coconal

members/zipingw/readme.md
=> init: zipingw

members/littleLane/readme.md
=> init: littleLane

members/terry-hjj/task1/ToDoApp/.eslintrc.cjs, members/terry-hjj/task1/ToDoApp/.gitignore, members/terry-hjj/task1/ToDoApp/README.md, members/terry-hjj/task1/ToDoApp/index.html, members/terry-hjj/task1/ToDoApp/package.json, members/terry-hjj/task1/ToDoApp/pnpm-lock.yaml, members/terry-hjj/task1/ToDoApp/src/App.tsx, members/terry-hjj/task1/ToDoApp/src/main.tsx, members/terry-hjj/task1/ToDoApp/src/vite-env.d.ts, members/terry-hjj/task1/ToDoApp/tsconfig.app.json, members/terry-hjj/task1/ToDoApp/tsconfig.json, members/terry-hjj/task1/ToDoApp/tsconfig.node.json, members/terry-hjj/task1/ToDoApp/vite.config.ts
=> task1: terry-hjj

members/Lym599593/task3/MyERC20.sol, members/Lym599593/task3/MyNFT.sol, members/Lym599593/task3/NFTMarket.sol, members/Lym599593/task3/readme.md
MyERC20: 
[0x89235eb6c1a9D30ef6F5bd6D6BC82bE82731462f], https://sepolia.etherscan.io/address/0x89235eb6c1a9D30ef6F5bd6D6BC82bE82731462f
MyNFT : 
[0x76BBDE97beB4B42E998b5e8AaF404EBF6F29178C], https://sepolia.etherscan.io/address/0x76BBDE97beB4B42E998b5e8AaF404EBF6F29178C
NFTMarket : 
[0xD6AE37Ff0268198DC717d582601D322a04282F7A], https://sepolia.etherscan.io/address/0xD6AE37Ff0268198DC717d582601D322a04282F7A
上架nft：
https://sepolia.etherscan.io/tx/0xbefa9bf6eac23209959b52d050ea6bee3fba3382ddc873036dd9d449c398e463
购买：
https://sepolia.etherscan.io/tx/0x1d70027b19cc9b51094072f904b80f58228b98431f2f4676e5fc55ec88d88971
=> task3：Lym599593

members/joy-joy-joy-joy-joy-joy-joy/readme.md
=> init: joy-joy-joy-joy-joy-joy-joy

members/ourai/task3/ERC20.sol, members/ourai/task3/ERC721.sol, members/ourai/task3/NFTMarket.sol, members/ourai/task3/readme.md
文件说明：
| 文件名 | Sepolia 地址 | 说明 |
| --- | --- | --- |
| `ERC20.sol` | [`0x49d22684Ec2feD0bFd9932C2756174B91b176842`](https://sepolia.etherscan.io/address/0x49d22684Ec2feD0bFd9932C2756174B91b176842) | ERC-20 代币 RaiCoin（RAIC） |
| `ERC721.sol` | [`0xab4662fFEAB06ecd20266510b947e58BD1002954`](https://sepolia.etherscan.io/address/0xab4662fFEAB06ecd20266510b947e58BD1002954) | ERC-721 代币 RaiE（RAIE） |
| `NFTMarket.sol` | [`0x17cB0240c669c988E2529077DFa98ff8A22c92fe`](https://sepolia.etherscan.io/address/0x17cb0240c669c988e2529077dfa98ff8a22c92fe) | NFT 市场 RaiGallery（RAIG） |
交易哈希：
| 哈希值 | 说明 |
| --- | --- |
| [`0x602ed9148b1d092e054612f45587af9e4e4fc691854ba993f29bf1f582f30f97`](https://sepolia.etherscan.io/tx/0x602ed9148b1d092e054612f45587af9e4e4fc691854ba993f29bf1f582f30f97) | 上架 token 1 |
| …
=> task3: ourai

members/zhangloveyan/task3/NFTMarket.sol, members/zhangloveyan/task3/ShouHuNFT.sol, members/zhangloveyan/task3/ShouHuToken.sol, members/zhangloveyan/task3/readme.md
task3 作业
| 文件名          | 合约地址                                   | 说明       |
| --------------- | ------------------------------------------ | ---------- |
| ShouHuToken.sol | 0x1d1c1f1217e9ac91aa3c72bc4eb458f39baae957 | ERC20 代币 |
| ShouHuNFT.sol   | 0x5c7122ded287d82cdc35b0d5da44bcf7ce8455c7 | ERC721 NFT |
| NFTMarket.sol   | 0x2fae6c0cbe090aad62fa8e48ee2de06d0c924f33 | 市场       |
上架 NFT 哈希：
0x19380876d94ea719871e593729abe519dea54120f1b29079bd8705921619cb47
https://sepolia.etherscan.io/tx/0x19380876d94ea719871e593729abe519dea54120f1b29079bd8705921619cb47
购买 NFT 哈希：
0x1d93c8db7e968fa76d17aeb3fca2f05aba41f5ba088edad96ebc434baa145501
https://sepolia.etherscan.io/tx/0x1d93c8db7e968fa76d17aeb3fca2f05aba41f5ba088edad96ebc434baa145501
=> task3: zhangloveyan

members/humbornjo/task3/ERC20.sol, members/humbornjo/task3/ERC721.sol, members/humbornjo/task3/NFTMarket.sol, members/humbornjo/task3/hash.md
- **init: place holder**
- **update: market done**
=> task3: humbornjo

members/vv1133/task3/NftExchange.sol, members/vv1133/task3/VVNft.sol, members/vv1133/task3/VVToken.sol, members/vv1133/task3/log.md
0xe6d7ec464bdbe1ab4a74071b3934fc0005aa93bde0eabae9c8ac729d41c4515e
0x136cf965ced676fa509c0aa70e10f5d93ae014b03efae548c33cb777b153b801
=> task3: vv1133

members/sheldon-xc/task3/README.md, members/sheldon-xc/task3/src/WFBNft.sol, members/sheldon-xc/task3/src/WFBNftMarketplace.sol, members/sheldon-xc/task3/src/WFBToken.sol
| 说明         | 地址                                                             |
| -------------- | ------------------------------------------------------------------ |
| WFBT(token)    | 0x187F1CB42A166f3A8fDA9161e2a9f8d70aE74c1E                         |
| WNFT(NFT)      | 0x1DEC59CDBA2B008f109f18875bD70338ea628B4c                         |
| NFTMarket      | 0x9D4b98c96BB5c3f8abD62f2b9b83262F34981E8d                         |
| 上架 NFT(id 2) | 0xfb2473d76200686516fca463848606dd28d6550e34ba10b901ee91784992ae87 |
| 购买 NFT(id 2) | 0x5b64ca338fc488f85186315d55f2d751ac30a7601503fd4be1d3f4dbdc3bc599 |
| 上架 NFT(id 3) | 0x6a3b1d1ebca2aba01f2137412b9e7274d3e2b9778aff9cfd1f4a8e59464d549f |
| 购买 NFT(id 3) | 0xdcfd88289a4a75c75323d4c6859ae2493d2d1c5d6d75dac40c23b03f1e7e391d |
=> task3: sheldon-xc

members/ymjrcc/task3/ERC20.sol, members/ymjrcc/task3/ERC721.sol, members/ymjrcc/task3/NFTMarket.sol, members/ymjrcc/task3/README.md
=> task3: ymjrcc

members/qiaopengjun5162/task3/ERC20.sol, members/qiaopengjun5162/task3/ERC721.sol, members/qiaopengjun5162/task3/NFTMarket.sol, members/qiaopengjun5162/task3/readme.md, members/qiaopengjun5162/task3/studyNotes.md
=> task3: qiaopengjun5162

members/flytam/task3/README.md, members/flytam/task3/contracts/market.sol, members/flytam/task3/contracts/nft.sol, members/flytam/task3/contracts/token.sol
[https://github.com/flytam](https://github.com/flytam)
[0x68570484F1373145bF45eb0364cbDE30dd1151D5](https://sepolia.etherscan.io/address/0x68570484f1373145bf45eb0364cbde30dd1151d5)
[0x610b6689d8426f1794cC10B640cC701263723f0b](https://sepolia.etherscan.io/address/0x610b6689d8426f1794cc10b640cc701263723f0b#code)
[0xD8490820c31bf1319E813Dc9354515299A1E63fC](https://sepolia.etherscan.io/address/0xd8490820c31bf1319e813dc9354515299a1e63fc#code)
- 上架 NFT
[0xfac1dadf95df68efd7f9a5b2cf7a05e196a3ceaabe0a433a5229a1027adf95c7](https://sepolia.etherscan.io/tx/0xfac1dadf95df68efd7f9a5b2cf7a05e196a3ceaabe0a433a5229a1027adf95c7)
- 购买 NFT
[0x0a8a798613b35ade06b835d1a8dc1e371c9ca805096553b2713eb49be030f2bb](https://sepolia.etherscan.io/tx/0x0a8a798613b35ade06b835d1a8dc1e371c9ca805096553b2713eb49be030f2bb) …
=> task3: flytam

members/LittleMoreInteresting/task3/README.md, members/LittleMoreInteresting/task3/contracts/HoraceNFT.sol, members/LittleMoreInteresting/task3/contracts/NFTMarket.sol, members/LittleMoreInteresting/task3/contracts/OBToken.sol
=> task3:LittleMoreInteresting

members/flytam/task7/.gitignore, members/flytam/task7/asconfig.json, members/flytam/task7/aspect/index.ts, members/flytam/task7/aspect/tsconfig.json, members/flytam/task7/contracts/counter.sol, members/flytam/task7/package-lock.json, members/flytam/task7/package.json, members/flytam/task7/project.config.json, members/flytam/task7/scripts/aspect-deploy.cjs, members/flytam/task7/scripts/batch-test.cjs, members/flytam/task7/scripts/bind.cjs, members/flytam/task7/scripts/contract-call.cjs, members/flytam/task7/scripts/contract-deploy.cjs, members/flytam/task7/scripts/contract-send.cjs, members/flytam/task7/scripts/create-account.cjs, members/flytam/task7/scripts/get-bound-account.cjs, members/flytam/task7/scripts/get-bound-aspect.cjs, members/flytam/task7/scripts/operation.cjs, members/flytam/task7/scripts/unbind.cjs
合约地址：0x763A5860fd0317B986951Da761A6300EB97D8d8b
aspectId：0x74Bca9bEB879B82003bCe9A4e70d8D24C746f6E0
=> task7: flytam

members/Aseisman/task7/.gitignore, members/Aseisman/task7/asconfig.json, members/Aseisman/task7/aspect/index.ts, members/Aseisman/task7/aspect/tsconfig.json, members/Aseisman/task7/contracts/counter.sol, members/Aseisman/task7/package-lock.json, members/Aseisman/task7/package.json, members/Aseisman/task7/project.config.json, members/Aseisman/task7/scripts/aspect-deploy.cjs, members/Aseisman/task7/scripts/batch-test.cjs, members/Aseisman/task7/scripts/bind.cjs, members/Aseisman/task7/scripts/contract-call.cjs, members/Aseisman/task7/scripts/contract-deploy.cjs, members/Aseisman/task7/scripts/contract-send.cjs, members/Aseisman/task7/scripts/create-account.cjs, members/Aseisman/task7/scripts/get-bound-account.cjs, members/Aseisman/task7/scripts/get-bound-aspect.cjs, members/Aseisman/task7/scripts/operation.cjs, members/Aseisman/task7/scripts/unbind.cjs
=> task7: Aseisman

members/linghuccc/task3/Market.sol, members/linghuccc/task3/Money.sol, members/linghuccc/task3/NFT.sol, members/linghuccc/task3/readme.md
ERC20 合约文件: Money.sol
ERC721 合约文件: NFT.sol
NFTMarket 合约文件: Market.sol
上架 NFT 的交易哈希: 0x49c96a385bff45796b9f1cbba5175f8eb26a937d98710f52a3bae853c3b1b707
https://sepolia.etherscan.io/tx/0x49c96a385bff45796b9f1cbba5175f8eb26a937d98710f52a3bae853c3b1b707
购买 NFT 的交易哈希: 0xb02ef95f7db375bffd792a12b00c24c6d3be5f018ba34b9e8b52e6bbe9c95078
https://sepolia.etherscan.io/tx/0xb02ef95f7db375bffd792a12b00c24c6d3be5f018ba34b9e8b52e6bbe9c95078
=> task3: linghuccc

members/warku123/task3/MyNFT.sol, members/warku123/task3/MyToken.sol, members/warku123/task3/NFTMarket.sol, members/warku123/task3/task3.md
=> task3: warku123

members/keyding/task7/aspect/index.ts
https://github.com/keyding/throttler-aspect
=> task7: keyding

members/ymiool/readme.md
=> init: ymiool

members/Georgiafab/task7/.gitignore, members/Georgiafab/task7/asconfig.json, members/Georgiafab/task7/aspect/index.ts, members/Georgiafab/task7/aspect/tsconfig.json, members/Georgiafab/task7/contracts/counter.sol, members/Georgiafab/task7/package-lock.json, members/Georgiafab/task7/package.json, members/Georgiafab/task7/project.config.json, members/Georgiafab/task7/scripts/aspect-deploy.cjs, members/Georgiafab/task7/scripts/batch-test.cjs, members/Georgiafab/task7/scripts/bind.cjs, members/Georgiafab/task7/scripts/contract-call.cjs, members/Georgiafab/task7/scripts/contract-deploy.cjs, members/Georgiafab/task7/scripts/contract-send.cjs, members/Georgiafab/task7/scripts/create-account.cjs, members/Georgiafab/task7/scripts/get-bound-account.cjs, members/Georgiafab/task7/scripts/get-bound-aspect.cjs, members/Georgiafab/task7/scripts/operation.cjs, members/Georgiafab/task7/scripts/unbind.cjs
=> task7: Georgiafab

members/carola-niu/task7/aspect/index.ts, members/carola-niu/task7/aspect/tsconfig.json
=> task7: carola-niu

members/zhangolve/task7/index.js
=> task7: zhangolve

members/Chen-Lun-Hao/task7/index.ts
https://github.com/Chen-Lun-Hao/throttler-aspect
=> task7: Chen-Lun-Hao

members/WAIYIN-tech/task3/src/Market.sol, members/WAIYIN-tech/task3/src/NftExchangeToken.sol, members/WAIYIN-tech/task3/src/WNft.sol
上架NFT hash: 0x95cefe22b77a1a95b6db2c02d34c6754ddf0dbcebce3e3d8fe750e5221c88c85 
购买NFT hash: 0xc6a3c0649d7821bdd03c48da9644d4fbe721385ad615d60a25cc2efa45e01b82
=> task3: WAIYIN-tech

members/carola-niu/task3/FederCoin.sol, members/carola-niu/task3/FederNFT.sol, members/carola-niu/task3/NFTMarket.sol, members/carola-niu/task3/README.md
>ERC20 contract address: 0x2bbBFaad3982C354Ae3aaA23aE4321Ae22079774
>ERC721 contract address: 0x4278147757aEea278fB7a2f1d20A500548Ca6DBF
>NFT Market contract address: 0xF9a94a208801194153936a5D6E5366cDd27BBB7e
>Listing NFT:0x4d2cd8e2eed2b9b418134b53347a961998e47b947c1d33e5b3c6b2e49d9838c6
etherscan:https://sepolia.etherscan.io/tx/0x4d2cd8e2eed2b9b418134b53347a961998e47b947c1d33e5b3c6b2e49d9838c6
>Buying NFT: 0x0168e2a09fa65ba937076ecd33e2451976f41fc23df23714dc6b7285d69634d2
etherscan:https://sepolia.etherscan.io/tx/0x0168e2a09fa65ba937076ecd33e2451976f41fc23df23714dc6b7285d69634d2
=> task3: carola-niu

members/ymiool/task3/.gitignore, members/ymiool/task3/contracts/NFT_exchange/FeMeCoin.sol, members/ymiool/task3/contracts/NFT_exchange/MeNFT.sol, members/ymiool/task3/contracts/NFT_exchange/NFTExchange.sol
- Token 地址 0x35A95f86ca010E451b60c61129333D9f9D53C8C6
https://optimism-sepolia.blockscout.com/token/0x35A95f86ca010E451b60c61129333D9f9D53C8C6
- NFT 地址 0x8e7cD1E802675d7caCB79D24d90E990e1dd08a45
https://optimism-sepolia.blockscout.com/token/0x8e7cD1E802675d7caCB79D24d90E990e1dd08a45
- Market 合约地址 0x2BFc0343c5516F651C664561F69911e8076FF11c
0xa560c113fa5fd7747f8d65ef6de63568c25de4ac36b152e7f83ffd33284d2682
https://optimism-sepolia.blockscout.com/tx/0xa560c113fa5fd7747f8d65ef6de63568c25de4ac36b152e7f83ffd33284d2682
0x374474f9e95de76caf785ccabe1aef78507cf6096265add9325878d448bae85b
https://optimism-sepolia.blockscout.com/tx/0x374474f9e95de76caf785ccabe1aef78507cf6096265add9325878d448bae85b
=> task3: ymiool

members/newraina/task1/.eslintrc.cjs, members/newraina/task1/.gitignore, members/newraina/task1/README.md, members/newraina/task1/index.html, members/newraina/task1/package.json, members/newraina/task1/pnpm-lock.yaml, members/newraina/task1/src/App.tsx, members/newraina/task1/src/components/AddToDo.tsx, members/newraina/task1/src/components/Header.tsx, members/newraina/task1/src/components/ToDoItem.tsx, members/newraina/task1/src/components/ToDoList.tsx, members/newraina/task1/src/hooks.ts, members/newraina/task1/src/index.css, members/newraina/task1/src/main.tsx, members/newraina/task1/src/vite-env.d.ts, members/newraina/task1/tsconfig.app.json, members/newraina/task1/tsconfig.json, members/newraina/task1/tsconfig.node.json, members/newraina/task1/vite.config.ts
preview: https://openbuild-bootcamp-task-1-todo-list.vercel.app/
https://github.com/user-attachments/assets/df25a9b5-1014-462f-89f5-ebff2c9404ca
=> task1: newraina

members/flytam/task9/readme.md, members/flytam/task9/sepolia-xxxx/.gitignore, members/flytam/task9/sepolia-xxxx/abis/NFTMarket.json, members/flytam/task9/sepolia-xxxx/docker-compose.yml, members/flytam/task9/sepolia-xxxx/networks.json, members/flytam/task9/sepolia-xxxx/package.json, members/flytam/task9/sepolia-xxxx/schema.graphql, members/flytam/task9/sepolia-xxxx/src/nft-market.ts, members/flytam/task9/sepolia-xxxx/subgraph.yaml, members/flytam/task9/sepolia-xxxx/tests/nft-market-utils.ts, members/flytam/task9/sepolia-xxxx/tests/nft-market.test.ts, members/flytam/task9/sepolia-xxxx/tsconfig.json
合约地址 [0x01c0C9cFa7fC5229B376317BDA7d09bC0f00a567](https://sepolia.etherscan.io/address/0x01c0c9cfa7fc5229b376317bda7d09bc0f00a567)
子图 
https://api.studio.thegraph.com/proxy/82840/sepolia-xxxx/version/latest/graphql
https://thegraph.com/studio/subgraph/sepolia-xxxx/
截图
=> task9: flytam

members/zhouBoom/task7/index.ts
=> task7: zhouBoom

members/ymiool/task7/throttler-aspect/aspect/index.ts
限流合约测试 Txs：https://betanet-scan.artela.network/address/0x4251ea092115746942C2fc09f21Ce54B0dd62227?tab=txs
（只有第一次第三次成功了）
=> task7: ymiool

members/newTap/README.md
=> init: newTap

members/newraina/task7/README.md, members/newraina/task7/aspect.ts
Aspect 部署命令：
```shell
node scripts/aspect-deploy.cjs --interval 10 --limit 2
```
可以看到所有的 Contract 调用中，只有第一次和第五次成功。
=> task7: newraina

members/bravehot/task7/index.ts
`npm run aspect:deploy -- --interval 5 --limit 2`
=> task7:bravehot

members/liudafengshu/task3/myERC20.sol, members/liudafengshu/task3/myERC721.sol, members/liudafengshu/task3/myNFTMarket.sol, members/liudafengshu/task3/readme.md
=> task3: liudafengshu

members/flexibility2/task8/readme.md
浏览器连接：
https://explorer-holesky.morphl2.io/address/0x71BcA794230292F96A40c6F0e227a5197127C3D9?tab=contact_code
验证截图：
=> task8: flexibility2

members/flexibility2/task7/.gitignore, members/flexibility2/task7/asconfig.json, members/flexibility2/task7/aspect/index.ts, members/flexibility2/task7/aspect/tsconfig.json, members/flexibility2/task7/contracts/counter.sol, members/flexibility2/task7/package-lock.json, members/flexibility2/task7/package.json, members/flexibility2/task7/project.config.json, members/flexibility2/task7/readme.md, members/flexibility2/task7/scripts/aspect-deploy.cjs, members/flexibility2/task7/scripts/batch-test.cjs, members/flexibility2/task7/scripts/bind.cjs, members/flexibility2/task7/scripts/contract-call.cjs, members/flexibility2/task7/scripts/contract-deploy.cjs, members/flexibility2/task7/scripts/contract-send.cjs, members/flexibility2/task7/scripts/create-account.cjs, members/flexibility2/task7/scripts/get-bound-account.cjs, members/flexibility2/task7/scripts/get-bound-aspect.cjs, members/flexibility2/task7/scripts/operation.cjs, members/flexibility2/task7/scripts/unbind.cjs
限流合约测试Txs:
https://betanet-scan.artela.network/address/0x3E39b9379Db37a15ed63e6eAD7E5d1f468Ae41d2
只成功三次
=> task7: flexibility2

members/Tsuizen/task7/index.ts
合约地址：0x2ee8C9eaCA8bF8FfaaEAbC7Aa9b5A6A3e43CFbE5
源码地址：https://github.com/Tsuizen/throttler-aspect
=> task7: Tsuizen

members/mosida/task7/index.ts
合约地址：0xd5Cb088322fc56612b9182a5E9Ff09B5bCB4E018
源码地址：https://github.com/mosida/throttler-aspect
=> task7: mosida

members/leonw111/readme.md
=> init: leonw
